apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-consumer
  namespace: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-consumer
  template:
    metadata:
      labels:
        app: inventory-consumer
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: consumer
          image: ghcr.io/yoshikrit/reservation-inventory-service:1
          imagePullPolicy: Always
          command: ["./consumer"]
          env:
            - name: OTEL_SERVICE_NAME
              value: "inventory-consumer"
          envFrom:
            - configMapRef:
                name: inventory-config
            - secretRef:
                name: inventory-secret
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
              ephemeral-storage: 50Mi
            limits:
              cpu: 100m
              memory: 64Mi
              ephemeral-storage: 100Mi
