apiVersion: v1
kind: Secret
metadata:
  name: inventory-secret
  namespace: inventory
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:secret@postgres:5432/inventory?sslmode=disable&TimeZone=Asia/Bangkok"
  POSTGRES_PASSWORD: "secret"
